version: '3'

services:

  car_simulator:
    image: python-microservices-base
    depends_on: 
      - activemq
    restart: always
    volumes:
      - ./car_simulator:/app


  app1:
    image: python-microservices-base
    depends_on:
      - activemq
    restart: always
    volumes:
      - ./app1:/app

  app2:
    image: python-microservices-base
    restart: always
    volumes:
      - ./app2:/app

  activemq:
    image: webcenter/activemq
