version: '3'

services:

  car_simulator:
    image: python-microservices-base
    depends_on: 
      - rabbitmq
    restart: always
    volumes:
      - ./car_simulator:/app

  db_saver:
    image: python-microservices-base
    depends_on:
      - rabbitmq
    restart: always
    volumes:
      - ./db_saver:/app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
