version: '3'

services:

  app1:
    image: python-microservices-base
    restart: always
    volumes:
      - ./app1:/app

  app2:
    image: python-microservices-base
    restart: always
    volumes:
      - ./app2:/app

  activemq:
    image: webcenter/activemq
